### ISSUE TITLE
Crash: Simple Night Vision (simplenightvision) encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by Ariostraza** [shawnbyday/SimpleNightVision#1]
Minecraft 1.19.3 Forge 44.1.2

Suppressed: net.minecraftforge.fml.ModLoadingException: Simple Night Vision (simplenightvision) encountered an error during the common_setup event phase
§7java.lang.NoSuchMethodError: 'void net.minecraft.world.item.CreativeModeTab.<init>(java.lang.String)'

Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.world.item.CreativeModeTab.<init>(java.lang.String)'

Crash report: [[Link]](https://justpaste.it/cgefc)

**Comment by shawnbyday** [comment]
@Ariostraza thank you for submitting issue to me! I updated mod quick and dirty just removing creative tab. Latest file is here: https://github.com/shawnbyday/SimpleNightVision/releases/tag/1.19.3-1.1 File should get updated on curse once they review.

Sorry accidentally checked 1.19.3 when uploading version 1.0 and didn't even realize it. Was definitely not ready! Also fixed that on curse.

If you have issues with this loading for you please let me know!
